CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Controllers/DocumentoPoderController.cs
using CL.Scotiabank.LegalPartner.SGL.APP;
using CL.Scotiabank.LegalPartner.SGL.Transversal.DTO;
using CL.Scotiabank.LegalPartner.SGL.Transversal.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CL.Scotiabank.LegalPartner.SGL.Web.Areas.EntradaCompleta.Controllers
{
    //[Produces("application/json")]
    //[Route("api/DocumentoPoder")]

    public class DocumentoPoderController : Controller
    {
        #region Members

        private IDocumentoPoderAPP _documentoPoderAPP;
        private dynamic logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
        private readonly string tituloMensajeError = Resources.TituloMensajeError;
        private readonly string cuerpoMensajeError = Resources.CuerpoMensajeError;


        #endregion

        #region Constructor

        public DocumentoPoderController(IDocumentoPoderAPP documentoPoderApp)
        {
            this._documentoPoderAPP = documentoPoderApp;
        }

        #endregion

        public ActionResult Index(EntradaCompletaDTO paramUsuario)
        {
            DocumentoPoderDTO documentoPoderDTO = new DocumentoPoderDTO();

            documentoPoderDTO.IdSGL = paramUsuario.Sgl;
            documentoPoderDTO.CodigoTipoPersona = Convert.ToInt32(paramUsuario.CodigoTipoPersona);
            documentoPoderDTO.CodigoPersona = paramUsuario.CodigoPersona;

            return View(documentoPoderDTO);
        }

        #region LISTAR        

        /// <summary>
        /// Método para listar los documentos.
        /// </summary>
        /// /// <param name="id"> Codigo de persona</param>
        /// <returns> Lista de documentos de poder</returns>
        public JsonResult ListarDocumentos(int id)
        {
            bool exitoso = false;
            
            try
            {
                if (id == Convert.ToInt32(Resources.valorCero))
                {
                    BadRequest();
                }

                BasePropertiesDTO mandatarioRetorno = this._documentoPoderAPP.ListarDocumentos(id);
                exitoso = true;

                return this.Json(new
                {
                    data = mandatarioRetorno.Resultado,
                    Exitoso = exitoso
                });
            }
            catch (Exception ex)
            {                
                logger.Error(ex, "Stopped program because of exception");

                return Json(new
                {
                    Exitoso = exitoso,
                    Titulo = tituloMensajeError,
                    Mensaje = cuerpoMensajeError
                });
            }
        }

        /// <summary>
        /// Método para obtener los poderes de lso documentos poder.
        /// </summary>
        /// <param name="id"> Codigo de persona</param>
        /// <param name="checkIn"> Valor que trae el checkbox de la lista</param>
        /// <param name="sgl">Id SGL </param>
        /// <returns>Lista de poderes de documentos de poder</returns>
        public JsonResult ObtenerDatosPoderes(int id, bool checkIn, int sgl)
        {
            bool exitoso = false;

            try
            {
                if (id == Convert.ToInt32(Resources.valorCero))
                {
                    BadRequest();
                }

                IList<DatosPoderesAndDesMatDTOResponse> mandatarioRetorno = this._documentoPoderAPP.ObtenerDatosPoderes(id, checkIn, sgl);

                return this.Json(new
                {
                    data = mandatarioRetorno
                });
            }
            catch (Exception ex)
            {
                logger.Error(ex, "Stopped program because of exception");

                return Json(new
                {
                    Exitoso = exitoso,
                    Titulo = tituloMensajeError,
                    Mensaje = cuerpoMensajeError
                });
            }
        }

        #endregion

        #region Grabar Documento de Poder

        /// <summary>
        /// Json que recibe el objeto para luego enviarlo a la paágina párcial Documento Poder
        /// </summary>
        /// <param name="datosModal"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult EnviaDataVistaParcial([FromBody]DocumentoPoderDTO datosModal)
        {
            if (ModelState.IsValid)
            {
                return Json(datosModal);
            }
            else
            {
                return Json("Error");
            }
        }
     //GET
        public ActionResult IngresarDocumento(DocumentoPoderDTO documentoPoderDTO)
        {
            //documentoPoderDTO.CodigoDocumentoRequest = 1442083;
            documentoPoderDTO.TipoDocumento = 1;

            if (documentoPoderDTO != null)
            {
                string codigoDocumento = Convert.ToString(documentoPoderDTO.CodigoDocumentoRequest);
                BasePropertiesDTO obtenerDocumentoRetorno = this._documentoPoderAPP.ObtenerDocumentoLegal(codigoDocumento);

                if (obtenerDocumentoRetorno != null)
                {
                    documentoPoderDTO.FechaDocumento = "";
                }
                else
                {

                }
                string codigoDocumentoRespuesta = Convert.ToString(documentoPoderDTO.CodigoDocumentoRequest);
                BasePropertiesDTO respuestLegalRetorno = this._documentoPoderAPP.ObtenerRespuestaLegal(codigoDocumento);

            }


            return View(documentoPoderDTO);
        }



        [HttpPost]
        ActionResult IngresarDocumentoGrabar(DocumentoPoderDTO documentoPoderDTO)
        {
            BasePropertiesDTO DocumentoRetorno = this._documentoPoderAPP.IngresarDocumentoPoder(documentoPoderDTO);

            return View();
        }

        public JsonResult ComboTipoDocumento()
        {
            IList<DropDownListDTO> lstDocumentos = new List<DropDownListDTO>();
            BasePropertiesDTO tipoDocumentoRetorno = this._documentoPoderAPP.ObtenerListaTipoDocumento();
            List<DocumentoPoderDTO> tipoDocumentoRetornofiltro = tipoDocumentoRetorno.Resultado;
            var listaTipoDocumentoPoderFiltro = tipoDocumentoRetornofiltro.Where(x => x.Codigo == 1 || x.Codigo == 2 || x.Codigo == 3 || x.Codigo == 8);

            Parallel.ForEach((IEnumerable<DocumentoPoderDTO>)listaTipoDocumentoPoderFiltro, (registro) =>
            {
                lstDocumentos.Add(new DropDownListDTO { id = registro.Codigo.ToString(), text = registro.Descripcion });
            });

            return Json(lstDocumentos);
        }

        public JsonResult ComboNotaria()
        {
            IList<DropDownListDTO> lstDocumentos = new List<DropDownListDTO>();
            BasePropertiesDTO notariaRetorno = this._documentoPoderAPP.ObtenerListaNotaria();
            //List<DocumentoPoderDTO> tipoDocumentoRetornofiltro = tipoDocumentoRetorno.Resultado;
            // var listaTipoDocumentoPoderFiltro = tipoDocumentoRetornofiltro.Where(x => x.Codigo == 1 || x.Codigo == 2 || x.Codigo == 3 || x.Codigo == 8);

            Parallel.ForEach((IEnumerable<DocumentoPoderDTO>)notariaRetorno.Resultado, (registro) =>
            {
                lstDocumentos.Add(new DropDownListDTO { id = registro.Codigo.ToString(), text = registro.Descripcion });
            });

            return Json(lstDocumentos);
        }


        public JsonResult ComboConservador()
        {
            IList<DropDownListDTO> lstDocumentos = new List<DropDownListDTO>();
            BasePropertiesDTO notariaRetorno = this._documentoPoderAPP.ObtenerConservadores();         

            Parallel.ForEach((IEnumerable<DocumentoPoderDTO>)notariaRetorno.Resultado, (registro) =>
            {
                lstDocumentos.Add(new DropDownListDTO { id = registro.Codigo.ToString(), text = registro.Descripcion });
            });

            return Json(lstDocumentos);
        }

        #endregion

        #region EDITAR Documento Poder
        public ActionResult EditarDocumento(DocumentoPoderDTO documentoPoderDTO)
        {
         

            if (documentoPoderDTO.CodigoDocumentoRequest != 0)
            {
                string codigoDocumento = Convert.ToString(documentoPoderDTO.CodigoDocumentoRequest);
                BasePropertiesDTO obtenerDocumentoRetorno = this._documentoPoderAPP.ObtenerDocumentoLegal(codigoDocumento);

                if (obtenerDocumentoRetorno != null)
                {
                    documentoPoderDTO.FechaDocumento = "";
                }
                else
                {

                }
                string codigoDocumentoRespuesta = Convert.ToString(documentoPoderDTO.CodigoDocumentoRequest);
                BasePropertiesDTO respuestLegalRetorno = this._documentoPoderAPP.ObtenerRespuestaLegal(codigoDocumento);

            }


            return View(documentoPoderDTO);
        }


        #endregion 

    }
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Views/DocumentoPoder/Index.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.DocumentoPoderDTO

@{
    Layout = null;
}
<h2 class="text-center">@ViewData["Title"]</h2>
<hr />
<div class="row" id="contenerdorListaDoc" style="width:100%">
    <div class="form-group col-md-12">
        <div>
            Mensaje de Advertencia: Si debe incorporar y revocar poderes, recuerde que primero debe ingresar la revocación.<br>
        </div>
        <div class="funkyradio-default">
            <input type="checkbox" name="radio" id="checkboxTodasSGL" />
            <label for="checkboxTodasSGL">Mostrar las escrituras de todas las SGL</label>
        </div>
        <div class="col-md-12" style="width:100%">
            <table id="listaDocumentoPoder" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th width="25%" style="text-align:center;">Tipo Documento <br> de Poder</th>
                        <th width="8%" style="text-align:center;">Fecha <br> Instrumento</th>
                        <th width="30%" style="text-align:center;">Notaria Documento</th>
                        <th width="8%" style="text-align:center;">N° <br> Repertorio</th>
                        <th width="8%" style="text-align:center;">Fecha <br> Sesión</th>
                        <th width="8%" style="text-align:center;">Fecha <br> Término</th>
                        <th width="12%" style="text-align:center;">Tipo Materia</th>
                        <th width="5%" style="text-align:center;">Disponible</th>
                    </tr>
                </thead>
            </table>
            <hr />
        </div>

        <div class="btn-group ">
            <button href='@Url.Action("IngresarDocumento", "DocumentoPoder", new { Area = "EntradaCompleta" })' id="btnIngresarDoc" class="btn btn-primario" style="margin-left: 10px;">
                <i class="fa fa-plus"></i> Agregar
            </button>
            <button href='@Url.Action("EditarMandatario")' id="btnEditarMandatario" class="btn btn-light">
                <i class="fa fa-edit"></i> Editar
            </button>
            <button id="btnEliminarMandatario" class="btn btn-secondary">
                <i class="fa fa-trash-alt" style="margin-right: 5px;"></i> Borrar
            </button>
            <button id="btnObservacionesMandatario" class="btn btn-light">
                <i class="fa fa-info-circle"></i> Traer Escritura
            </button>
            <button id="btnObservacionesMandatario" class="btn btn-light">
                <i class="fa fa-info-circle"></i> Previo Informe Poder
            </button>
            <button id="btnObservacionesMandatario" class="btn btn-light">
                <i class="fa fa-info-circle"></i> Previo Informe Revocación
            </button>
        </div>
    </div>
</div>


@*Contenedor de Tabs para Poderes y Revocaciones*@
<div class="row" id="contenedorPoderesyRevocaciones" style="width:100%">
    <div class="form-group col-md-12">
        <ul class="nav nav-tabs" id="myTab" role="tablist">

            <li class="nav-item">
                <a class="nav-link active" id="doc-tab" data-toggle="tab" href="#documento" role="tab" aria-controls="home" aria-selected="true">Documento</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="mandatarioGrupo-tab" data-toggle="tab" href="#mandatarioGrupo" role="tab" aria-controls="profile" aria-selected="false">Mandatarios/Grupos</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" id="poder-tab" data-toggle="tab" href="#poder" role="tab" aria-controls="contact" aria-selected="false">Poderes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="revocacion-tab" data-toggle="tab" href="#revocaciones" role="tab" aria-controls="contact" aria-selected="false">Revocaciones</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="documento" role="tabpanel" aria-labelledby="modLeg-tab">
                @*Vista Partial Documento*@
            </div>
            <div class="tab-pane fade" id="mandatarioGrupo" role="tabpanel" aria-labelledby="estatutos-tab">
                @*Vista Partial Mandatarios y Grupos*@
            </div>
            <div class="tab-pane fade" id="poderes" role="tabpanel" aria-labelledby="estatutos-tab">

                @*Vista Partial Poderes*@
            </div>
            <div class="tab-pane fade" id="revocaciones" role="tabpanel" aria-labelledby="estatutos-tab">

                @*Vista Partial Revocaciones*@
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

    $('#contenedorPoderesyRevocaciones').css('display', 'none');

    $(document).on('click', '#poder-tab', function (e) {

        $("#checkboxTodasSGL").prop('disabled', true);
        $("#checkboxTodasSGL").prop('checked', false);

        //DOCUMENTO PODER*************************************************************************************
        //LISTAR_________________________________________________________________________________________
        var id = @Model.CodigoPersona;;
        var check = false;
        var sgl = @Model.IdSGL;

        ListarDocumento(id);

        function ListarDocumento(id) {
            $.ajax({
                method: "GET",
                url: '@Url.Action("ListarDocumentos", "DocumentoPoder")',
                dataType: 'json',
                data: {id: id}
            })
            .done(function (data) {

                if (!data.exitoso) {
                    titulo = data.titulo;
                    mensaje = data.mensaje;
                    MuestraMensajes(titulo, mensaje);
                }
                else if (data.data.length != 0) {
                    cargaTabla(id, check, sgl);
                }
                else {
                    $('#titulo-modal-mensaje').html('Mensaje: Poderes y Revocaciones');
                    $('#cuerpo-modal-mensaje').html('Primero debe ingresar DATOS CONSTITUCIÓN y / o MODIFICACIÓN Y LEGALIZACIÓN.');
                    $('#modal-mensaje').modal('show');
                    $('#modLeg-tab').trigger('click');
                }
            })
            .fail(function () {

            });
        };

        $('#checkboxTodasSGL').change(function () {

            if ($(this).is(":checked")) {
                id = 372400;
                check = true;
                ListarDocumento(id);
            }
            else {
                id = 372400;
                check = false;
                ListarDocumento(id);
            }
        });

        function cargaTabla(id, check, sgl) {
            $("#checkboxTodasSGL").prop('disabled', true);

            $('#listaDocumentoPoder').DataTable({
                'ajax': '/EntradaCompleta/DocumentoPoder/ObtenerDatosPoderes?id=' + id + "&checkIn=" + check + "&sgl=" + sgl,
                'language': languageGrid,
                "processing": true,
                "serverSide": false,
                "destroy": true,
                'type': 'GET',
                'columns': [
                    {
                        'data': 'descripcionTipoPoder',
                        'visible': true
                    },
                    {
                        'data': 'fechaDocumento',
                        'visible': true
                    },
                    {
                        'data': 'notaria',
                        'visible': true
                    },
                    {
                        'data': 'numeroDocumento',
                        'visible': true
                    },
                    {
                        'data': 'fechaSesionDirectorio',
                        'visible': true
                    },
                    {
                        'data': 'fechaTerminoPoder',
                        'visible': true
                    },
                    {
                        'data': 'descripcionMateria',
                        'visible': true
                    },
                    {
                        data: "doc_est_csu",
                        render: function (data, type, row) {
                            if (type === 'display') {
                                return '<input type="checkbox" class="editor-active" style="text-align:center; vertical-align: middle;" disabled>';
                            }
                            return data;
                        },
                        className: "dt-body-center"
                    }
                ],
                "initComplete": function (settings, json) {

                    var table = $('#listaDocumentoPoder').DataTable();

                    if (!table.data().count() && check == true) {

                        $('#titulo-modal-mensaje').html('Mensaje: Poderes y Revocaciones');
                        $('#cuerpo-modal-mensaje').html('No tiene escrituras.');
                        $('#modal-mensaje').modal('show');
                    }

                    $("#checkboxTodasSGL").prop('disabled', false);
                },
                rowCallback: function (row, data) {

                    $('input.editor-active', row).prop('checked', data.doc_est_csu != 1);
                }
            });
        };

        function MuestraMensajes(titulo, mensaje) {

            $('#titulo-modal-mensaje').html(titulo);
            $('#cuerpo-modal-mensaje').html(mensaje);
            $('#modal-mensaje').modal('show');

            $('#btn-cerrar-modal-mensaje').html("Volver");

            $('#btn-cerrar-modal-mensaje').off("click").on("click", function (e) {
                $("#modal-mensaje").modal('hide');
                return;
            });
        }

    });

    $(document).on('click', '#btnIngresarDoc', function (e) {

        //e.preventDefault();
       //window.scrollTo(0, 0);

        $('#contenerdorListaDoc').css('display', 'none');

        $('#contenedorPoderesyRevocaciones').css('display', 'block');

                var codSgl = @Model.IdSGL;
                var rut = @Model.Rut;
                var codigoPersona = @Model.CodigoPersona;
                var codigoTipoPersona = @Model.CodigoTipoPersona;
                var codigoRevocacion = @Model.CodigoRevocacion;
                var codigoTipoPoder = @Model.TipoPoder;
                console.log('revocacion ' + codigoTipoPoder)
                @*var estadoConsulta = @Model.EstadoConsulta;
                console.log('revocacion ' + estadoConsulta)*@

                var datosModal = {
                    Rut: rut,
                    Sgl: codSgl,
                    CodigoPersona: codigoPersona,
                    CodigoTipoPersona: codigoTipoPersona,
                    CodigoRevocacion: codigoRevocacion,
                    CodigoDocumentoRequest: "0",
                    TipoPoder: codigoTipoPoder
                };

        var objeto = JSON.stringify(datosModal); $.ajax({

            url: "@Url.Action("EnviaDataVistaParcial", "DocumentoPoder")",
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: objeto,
            success: function (data) {
                console.log(data)
                @*if (@Model.CodigoTipoPersona != 0) {*@
                    //Cargo Tab Constitucion y Legalizacion como vista partial pasando parametros

                $("#documento").load('/EntradaCompleta/DocumentoPoder/IngresarDocumento', data);
                //Cargo Tab Constitucion y Legalizacion como vista partial pasando parametros
                    $("#mandatarioGrupo").load('/EntradaCompleta/MandatarioGrupo/Index'/*, data*/);

                //}
                //Cargo Tab Constitucion y Legalizacion como vista partial pasando parametros
                    // $("#poder").load('/EntradaCompleta/Poderes/Index', data);
                //Cargo Tab Constitucion y Legalizacion como vista partial pasando parametros
                    // $("#revocacion").load('/EntradaCompleta/Revocaciones/Index', data);

            }
        });
    });

</script>