CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Controllers/ConservadorController.cs
using CL.Scotiabank.LegalPartner.SGL.APP;
using CL.Scotiabank.LegalPartner.SGL.Transversal.DTO;
using CL.Scotiabank.LegalPartner.SGL.Transversal.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CL.Scotiabank.LegalPartner.SGL.Web.Areas.Mantenedores.Controllers
{
    [ActionsFilter]
    public class ConservadorController : Controller
    {
        #region Members
        
        private readonly string baseUriConservadores = Resources.ConservadorUrl;
        private dynamic logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

        private readonly IConservadorAPP _conservadorAPP;
        
        #endregion

        #region Constructor

        public ConservadorController(IConservadorAPP conservadorAPP)
        {
            this._conservadorAPP = conservadorAPP;
        }

        #endregion

        //[ActionsFilter]
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult List()
        {
            BasePropertiesDTO conservadorRetorno = this._conservadorAPP.Get();

            return this.Json(new
            {
                data = conservadorRetorno.Resultado
            });
        }


        //[ActionsFilter]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ActionsFilter]
        public IActionResult Create(ConservadorDTO conservadorDTO)
        {
            try
            {
                BasePropertiesDTO conservadorRetorno = this._conservadorAPP.Create(conservadorDTO);

                if (conservadorRetorno != null)
                {
                    int codigoRetorno = conservadorRetorno.CodigoRetorno;

                    if (codigoRetorno == (int)MantenedoresEstados.Exitoso)
                    {
                        @TempData["Exito"] = true;
                        @TempData["TituloMensaje"] = "Creación Exitosa";
                        @TempData["CuerpoMensaje"] = "Se ha creado el registro exitosamente.";
                        return RedirectToAction("Index");
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroExistente)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Registro Existente";
                        @TempData["CuerpoMensaje"] = "El registro que está intentando crear ya existe, intente con otra descripción.";
                    }
                    else
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error";
                        @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                    }
                }
                else
                {
                    @TempData["Error"] = true;
                    @TempData["TituloMensaje"] = "Error";
                    @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                }

                return View(conservadorDTO);

            }
            catch (Exception ex )
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                BasePropertiesDTO conservador = this._conservadorAPP.Get(id);

                return PartialView((ConservadorDTO)conservador.Resultado);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            try
            {
                BasePropertiesDTO conservador = this._conservadorAPP.Get(id);

                return View((ConservadorDTO)conservador.Resultado);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Edit(ConservadorDTO conservadorDTO)/*modificar el conservador DTO a base en la primera linea de codigo*/
        {
            try
            {
                BasePropertiesDTO conservadorRetorno = this._conservadorAPP.Edit(conservadorDTO);

                if (conservadorRetorno != null)
                {
                    int codigoRetorno = conservadorRetorno.CodigoRetorno;

                    if (codigoRetorno == (int)MantenedoresEstados.Exitoso)
                    {
                        @TempData["Exito"] = true;
                        @TempData["TituloMensaje"] = "Edición Exitosa";
                        @TempData["CuerpoMensaje"] = "Se ha editado el registro exitosamente.";
                        return RedirectToAction("Index");
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroNoExistente)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Edición de Registro No Existente";
                        @TempData["CuerpoMensaje"] = "El registro que está intentando editar no existe, intente con otro.";
                    }
                    else
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error";
                        @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                    }
                }
                else
                {
                    @TempData["Error"] = true;
                    @TempData["TituloMensaje"] = "Error";
                    @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                }

                return View(conservadorDTO);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
                   
        }
        
        public IActionResult Delete(int id)
        {
            try
            {
                BasePropertiesDTO conservador = this._conservadorAPP.Get(id);

                return View((ConservadorDTO)conservador.Resultado);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }

            
        }

        [HttpPost]
        public IActionResult Delete(ConservadorDTO conservadorDTO)
        {
            try
            {
                BasePropertiesDTO conservadorRetorno = this._conservadorAPP.Delete(conservadorDTO);

                if (conservadorRetorno != null)
                {
                    int codigoRetorno = conservadorRetorno.CodigoRetorno;

                    if (codigoRetorno == (int)MantenedoresEstados.Exitoso)
                    {
                        @TempData["Exito"] = true;
                        @TempData["TituloMensaje"] = "Eliminación Exitosa";
                        @TempData["CuerpoMensaje"] = "Se ha eliminado el registro exitosamente.";
                        return RedirectToAction("Index");
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroNoExistente)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Eliminación de Registro No Existente";
                        @TempData["CuerpoMensaje"] = "El registro que está intentando eliminar no existe, intente con otro.";
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroUtilizado)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Registro Utilizado por Tabla";
                        @TempData["CuerpoMensaje"] = "No se ha podido eliminar el registro, porque está siendo utilizado por otra tabla.";
                    }
                    else
                    {

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/Conservador/Create.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.ConservadorDTO

@{
    ViewData["Title"] = "Ingresar Registro Tabla Conservador";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label col-md-6" style="font-size: 15px;"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button id="btn-registrar" class="btn btn-primario">
                        <i class="fa fa-plus"></i> Registrar
                    </button>
                    <button id="btn-limpiar" class="btn btn-default">
                        <i class="fa fa-brush"></i> Limpiar
                    </button>
                    <a href='@Url.Action("Index", "Conservador")' class="btn btn-secondary">
                        <i class="fa fa-ban"></i> Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-registrar').on("click", function (e) {
                e.preventDefault();
                
                var formulario = $('#formulario');
                
                if (formulario.valid()) {
                    $('#titulo-modal-confirmar').html('Confirmar Creación');
                    $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea crear el registro ?');
                    $('#modal-confirmar').modal('show');
                }
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/Conservador/Delete.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.ConservadorDTO

@{
    ViewData["Title"] = "Eliminar Registro Tabla Conservador";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <form asp-action="Delete" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
        <h5>¿Está seguro que desea eliminar este registro?</h5>
        <dl class="dl-horizontal" style="text-align:center;">
            <dt>
                <!-- @Html.DisplayNameFor(model => model.Codigo) -->
                <label asp-for="Codigo" class="control-label col-md-6" style="font-size: 15px;"></label>
            </dt>
            <dd>
                <input asp-for="Codigo" class="form-control" readonly/>
                <!-- @Html.DisplayFor(model => model.Codigo) -->
            </dd>
            <dt>
                <!-- @Html.DisplayNameFor(model => model.Descripcion) -->
                <label asp-for="Descripcion"></label>                
            </dt>
            <dd>
                <input asp-for="Descripcion" class="form-control" readonly/>
                <!-- @Html.DisplayFor(model => model.Descripcion) -->
            </dd>
        </dl>
        <div class="form-group">
            <button id="btn-eliminar" class="btn btn-primario">
                <i class="fa fa-trash-alt"></i> Eliminar
            </button>
            <a href='@Url.Action("Index", "Conservador")' class="btn btn-secondary">
                <i class="fa fa-ban"></i> Cancelar
            </a>
        </div>
    </form>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-eliminar').on("click", function (e) {
                e.preventDefault();

                $('#titulo-modal-confirmar').html('Confirmar Eliminación');
                $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea eliminar el registro ?');
                $('#modal-confirmar').modal('show');
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                //$("#modal-loading").modal('show');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/Conservador/Details.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.ConservadorDTO

@{
    Layout = null;
    <!-- ViewData["Title"] = "Detalle Registro Tabla Conservador"; -->
}

<dl class="dl-horizontal col-12 col-sm-12 col-md-12 col-lg-12" style="text-align:center;">
    <dt>
        <label asp-for="Descripcion" style="font-size:15px;"></label>                
    </dt>
    <dd>
        <input asp-for="Descripcion"  class="form-control" style="width:100%" readonly/>
    </dd>
</dl>

<script type="text/javascript">
    $(function (e) {
        $('#Codigo').val($('#Codigo').val().trim());
        $('#Descripcion').val($('#Descripcion').val().trim());
    });
</script>

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/Conservador/Edit.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.ConservadorDTO

@{
    ViewData["Title"] = "Editar Registro Tabla Conservador";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
                @Html.HiddenFor(model => model.Codigo)
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label col-md-6" style="font-size: 15px;"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button id="btn-editar" class="btn btn-primario">
                        <i class="fa fa-pen"></i> Editar
                    </button>
                    <button id="btn-limpiar" class="btn btn-default">
                        <i class="fa fa-brush"></i> Limpiar
                    </button>
                    <a href='@Url.Action("Index", "Conservador")' class="btn btn-secondary">
                        <i class="fa fa-ban"></i> Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-editar').on("click", function (e) {
                e.preventDefault();

                var formulario = $('#formulario');

                if (formulario.valid()) {
                    $('#titulo-modal-confirmar').html('Confirmar Edición');
                    $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea editar el registro ?');
                    $('#modal-confirmar').modal('show');
                }
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/Conservador/Index.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.ConservadorDTO

@{
    ViewData["Title"] = "Conservadores";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr/>
<div class="col-md-12">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>ID Conservadores</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
    <hr />
    <p class="text-right">
        <a class="btn btn-primario" href=@Url.Action("Create", "Conservador")>Ingresar Registro</a>
    </p>
</div>
    @section Scripts{
        <script type="text/javascript">

        $(function () {


            var exito = '@TempData["Exito"]';

            if( exito == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            //$("#exampleModal").on("show.bs.modal", function (e) {

            //    var button = $(e.relatedTarget); // Button that triggered the modal

            //    var url = button.attr("href");

            //    $(this).find(".modal-body").load(url);

            //});

            $('#modal-detalle').on('hidden.bs.modal', function (e) {

                // remove the bs.modal data attribute from it
                $(this).removeData('bs.modal');

                // and empty the modal-content element
                $('#modal-detalle .modal-body').empty();
                $('#modal-detalle .modal-body').html('<img src="../images/loading.gif"/>');
            });

            $(document).on('click', '#example #btnDetalle', function (e) {
                e.preventDefault();

                var button = $(e.currentTarget);
                var url = button.attr('href');

                $('#modal-loading').modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

                $('#titulo-modal-detalle').html('Detalle Registro Tabla Conservador');

                //$.ajax({
                //    method: "GET",
                //    url: url
                //})
                //.done(function( msg ) {
                //    $('#modal-detalle .modal-body').html(msg);
                //    setTimeout(function(){
                //        $('#modal-loading').modal('hide');
                //    }, 500);
                //});

                $('#modal-detalle .modal-body').load(url, function(data){
                    setTimeout(function(){
                        $('#modal-loading').modal('hide');
                        $('#modal-detalle').modal('show');
                    }, 500);
                });
            });

            @*$('#dropExample').select2({
                data: @Html.Raw(Model.listaDropDown),
                dataType: 'json',
                theme: 'bootstrap4'
            });*@
            

            @*$('#dropExample').select2({
                ajax: {
                    url: '@Url.Action("ListarDrop")',
                    dataType: 'json',
                    processResults: function (data) {
                        console.log(data);
                        // Tranforms the top-level key of the response object from 'items' to 'results'
                        return {
                            results: data
                        };
                    }
                }
            });*@


            $('#example').DataTable({
                'ajax': '@Url.Action("List")',
                'language': languageGrid,
                "processing": true,
                "serverSide": false,
                'type': 'GET',
                responsive: true,
                'columns': [
                    {
                        'data': 'codigo',
                        'visible': false
                    },
                    { 'data': 'descripcion' }

                ],
                'columnDefs': [
                    {
                        'width': "130px",
                        'targets': [2],
                        'render': function (data, type, row) {
                            return '<a style="padding:0px;margin-left:10px;" class="btn btn-default" id="btnEditar" href="@Url.Action("Edit", "Conservador")/' + row.codigo + '"><div class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="Editar"></div></a>'
                                    +'<a style="padding:0px;margin-left:20px;" class="btn btn-default" id="btnDetalle" href="@Url.Action("Details", "Conservador")/' + row.codigo + '"><div class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Detalle"></div></a>'
                                    +'<a style="padding:0px;margin-left:20px;" class="btn btn-default" id="btnEliminar" href="@Url.Action("Delete", "Conservador")/' + row.codigo + '"><div class="fa fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Eliminar"></div></a>';
                        }
                    }
                ]
            });

            $('[data-toggle="tooltip"]').tooltip();

        });

        </script>
    }