CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Controllers/GrupoUsuarioController.cs
using CL.Scotiabank.LegalPartner.SGL.APP;
using CL.Scotiabank.LegalPartner.SGL.Transversal.DTO;
using CL.Scotiabank.LegalPartner.SGL.Transversal.Utilities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CL.Scotiabank.LegalPartner.SGL.Web.Areas.Mantenedores.Controllers
{
    [ActionsFilter]
    public class GrupoUsuarioController : Controller
    {
        #region Members
        
        private readonly string baseUriGrupoUsuarios = Resources.GrupoUsuariosUrl;
        private dynamic logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

        private readonly IGrupoUsuarioAPP _grupoUsuarioAPP;
        
        #endregion

        #region Constructor

        public GrupoUsuarioController(IGrupoUsuarioAPP grupoUsuarioAPP)
        {
            this._grupoUsuarioAPP = grupoUsuarioAPP;
        }

        #endregion

        public IActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        public JsonResult List()
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Get();

                return this.Json(new
                {
                    data = grupoUsuarioRetorno.Resultado
                });

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return null;
            }
        }

        public JsonResult ListDropdown()
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Get();

                List<DropDownListDTO> listaDTO = new List<DropDownListDTO>();

                Parallel.ForEach((IEnumerable<GrupoUsuarioDTO>)grupoUsuarioRetorno.Resultado, (registro) => 
                {
                    listaDTO.Add(new DropDownListDTO { id = registro.Codigo.ToString(), text = registro.Descripcion });
                });
            
                return this.Json(listaDTO);

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return null;
            }
        }        

        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Create(GrupoUsuarioDTO grupoUsuarioDTO)
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Create(grupoUsuarioDTO);

                if (grupoUsuarioRetorno != null)
                {
                    int codigoRetorno = grupoUsuarioRetorno.CodigoRetorno;

                    if (codigoRetorno == (int)MantenedoresEstados.Exitoso)
                    {
                        @TempData["Exito"] = true;
                        @TempData["TituloMensaje"] = "Creación Exitosa";
                        @TempData["CuerpoMensaje"] = "Se ha creado el registro exitosamente.";
                        return RedirectToAction("Index");
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroExistente)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Registro Existente";
                        @TempData["CuerpoMensaje"] = "El registro que está intentando crear ya existe, intente con otra descripción.";
                    }
                    else
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error";
                        @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                    }
                }
                else
                {
                    @TempData["Error"] = true;
                    @TempData["TituloMensaje"] = "Error";
                    @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                }

                return View(grupoUsuarioDTO);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Get(id);

                return PartialView((GrupoUsuarioDTO)grupoUsuarioRetorno.Resultado);

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Get(id);

                return View((GrupoUsuarioDTO)grupoUsuarioRetorno.Resultado);
            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(GrupoUsuarioDTO grupoUsuarioDTO)
        {
            try
            {
                BasePropertiesDTO grupoUsuarioRetorno = this._grupoUsuarioAPP.Edit(grupoUsuarioDTO);

                if (grupoUsuarioRetorno != null)
                {
                    int codigoRetorno = grupoUsuarioRetorno.CodigoRetorno;

                    if (codigoRetorno == (int)MantenedoresEstados.Exitoso)
                    {
                        @TempData["Exito"] = true;
                        @TempData["TituloMensaje"] = "Edición Exitosa";
                        @TempData["CuerpoMensaje"] = "Se ha editado el registro exitosamente.";
                        return RedirectToAction("Index");
                    }
                    else if (codigoRetorno == (int)MantenedoresEstados.RegistroNoExistente)
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error - Edición de Registro No Existente";
                        @TempData["CuerpoMensaje"] = "El registro que está intentando editar no existe, intente con otro.";
                    }
                    else
                    {
                        @TempData["Error"] = true;
                        @TempData["TituloMensaje"] = "Error";
                        @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                    }
                }
                else
                {
                    @TempData["Error"] = true;
                    @TempData["TituloMensaje"] = "Error";
                    @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";
                }

                return View(grupoUsuarioDTO);            

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = "Mensaje: Error";
                @TempData["CuerpoMensaje"] = "Ha ocurrido un error inesperado, inténtelo de nuevo más tarde o conéctese con el administrador del sistema.";

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/GrupoUsuario/Create.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.GrupoUsuarioDTO

@{
    ViewData["Title"] = "Ingresar Registro Tabla Grupo Usuario";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>                
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label col-md-6" style="font-size: 15px;"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button id="btn-registrar" class="btn btn-primario">
                        <i class="fa fa-plus"></i> Registrar
                    </button>
                    <button id="btn-limpiar" class="btn btn-default">
                        <i class="fa fa-brush"></i> Limpiar
                    </button>
                    <a href='@Url.Action("Index", "GrupoUsuario")' class="btn btn-secondary">
                        <i class="fa fa-ban"></i> Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-registrar').on("click", function (e) {
                e.preventDefault();
                
                var formulario = $('#formulario');
                
                if (formulario.valid()) {
                    $('#titulo-modal-confirmar').html('Confirmar Creación');
                    $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea crear el registro ?');
                    $('#modal-confirmar').modal('show');
                }
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/GrupoUsuario/Delete.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.GrupoUsuarioDTO

@{
    ViewData["Title"] = "Eliminar Registro Tabla Grupo Usuario";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <form asp-action="Delete" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
        <h5>¿Está seguro que desea eliminar este registro?</h5>
        <dl class="dl-horizontal" style="text-align:center;">
            <dt>
                <!-- @Html.DisplayNameFor(model => model.Codigo) -->
                <label asp-for="Codigo" class="control-label col-md-6" style="font-size: 15px;"></label>
            </dt>
            <dd>
                <input asp-for="Codigo" class="form-control" readonly/>
                <!-- @Html.DisplayFor(model => model.Codigo) -->
            </dd>
            <dt>
                <!-- @Html.DisplayNameFor(model => model.Descripcion) -->
                <label asp-for="Descripcion"></label>                
            </dt>
            <dd>
                <input asp-for="Descripcion" class="form-control" readonly/>
                <!-- @Html.DisplayFor(model => model.Descripcion) -->
            </dd>
        </dl>
        <div class="form-group">
            <button id="btn-eliminar" class="btn btn-primario">
                <i class="fa fa-trash-alt"></i> Eliminar
            </button>
            <a href='@Url.Action("Index", "GrupoUsuario")' class="btn btn-secondary">
                <i class="fa fa-ban"></i> Cancelar
            </a>
        </div>
    </form>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-eliminar').on("click", function (e) {
                e.preventDefault();

                $('#titulo-modal-confirmar').html('Confirmar Eliminación');
                $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea eliminar el registro ?');
                $('#modal-confirmar').modal('show');
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                //$("#modal-loading").modal('show');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/GrupoUsuario/Details.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.GrupoUsuarioDTO

@{
    Layout = null;
    <!-- ViewData["Title"] = "Detalle Registro Tabla GrupoUsuario"; -->
}

<dl class="dl-horizontal" style="text-align:center;">
    <dt>
        <label asp-for="Codigo" style="font-size:15px;"></label>
    </dt>
    <dd>
        <input asp-for="Codigo" class="form-control" readonly/>
    </dd>
    <dt>
        <label asp-for="Descripcion" style="font-size:15px;"></label>                
    </dt>
    <dd>
        <input asp-for="Descripcion"  class="form-control" readonly/>
    </dd>
</dl>

<script type="text/javascript">
    $(function (e) {
        $('#Codigo').val($('#Codigo').val().trim());
        $('#Descripcion').val($('#Descripcion').val().trim());
    });
</script>

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/GrupoUsuario/Edit.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.GrupoUsuarioDTO

@{
    ViewData["Title"] = "Editar Registro Tabla Grupo Usuario";
}

<div class="text-center">
    <h4>@ViewData["Title"]</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Edit" class="col-xl-8 offset-xl-2 col-md-8 offset-md-2" id="formulario">
                @Html.HiddenFor(model => model.Codigo)
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label col-md-6" style="font-size: 15px;"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button id="btn-editar" class="btn btn-primario">
                        <i class="fa fa-pen"></i> Editar
                    </button>
                    <button id="btn-limpiar" class="btn btn-default">
                        <i class="fa fa-brush"></i> Limpiar
                    </button>
                    <a href='@Url.Action("Index", "GrupoUsuario")' class="btn btn-secondary">
                        <i class="fa fa-ban"></i> Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(function (e) {

            var error = '@TempData["Error"]';

            if( error == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#btn-limpiar').on("click", function () {
                $('#formulario input[type="text"]').val('');
            });

            $('#btn-editar').on("click", function (e) {
                e.preventDefault();

                var formulario = $('#formulario');

                if (formulario.valid()) {
                    $('#titulo-modal-confirmar').html('Confirmar Edición');
                    $('#cuerpo-modal-confirmar').html('¿ Está seguro que desea editar el registro ?');
                    $('#modal-confirmar').modal('show');
                }
            });

            $('#btn-aceptar-modal-confirmar').on("click", function (e) {

                $('#formulario').submit();
                $("#modal-confirmar").modal('hide');

                $("#modal-loading").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

            });

            $('#btn-cancelar-modal-confirmar').on("click", function (e) {
                $("#modal-confirmar").modal('hide');
            });
        });


    </script>
}

CL.Scotiabank.LegalPartner.SGL.Web/Areas/Mantenedores/Views/GrupoUsuario/Index.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.GrupoUsuarioDTO

@{
    ViewData["Title"] = "Grupo Usuario";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />
<div class="col-md-12">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>ID GrupoUsuario</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
    <hr />
    <p class="text-right">
        <a class="btn btn-primario" href=@Url.Action("Create", "GrupoUsuario")>Ingresar Nuevo Registro</a>
    </p>
</div>
@section Scripts{
    <script type="text/javascript">

        $(function () {


            var exito = '@TempData["Exito"]';

            if( exito == 'True')
            {
                $('#titulo-modal-mensaje').html('@TempData["TituloMensaje"]');
                $('#cuerpo-modal-mensaje').html('@TempData["CuerpoMensaje"]');

                $('#modal-mensaje').modal('show');
            }

            $('#modal-detalle').on('hidden.bs.modal', function (e) {

                // remove the bs.modal data attribute from it
                $(this).removeData('bs.modal');

                // and empty the modal-content element
                $('#modal-detalle .modal-body').empty();
                $('#modal-detalle .modal-body').html('<img src="../images/loading.gif"/>');
            });

            $(document).on('click', '#example #btnDetalle', function (e) {
                e.preventDefault();

                var button = $(e.currentTarget);
                var url = button.attr('href');

                $('#modal-loading').modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });

                $('#titulo-modal-detalle').html('Detalle Registro Tabla Grupo Usuario');

                $('#modal-detalle .modal-body').load(url, function(data){
                    setTimeout(function(){
                        $('#modal-loading').modal('hide');
                        $('#modal-detalle').modal('show');
                    }, 500);
                });
            });
        
            $('#example').DataTable({
                'ajax': '@Url.Action("List")',
                'language': languageGrid,
                "processing": true,
                "serverSide": false,
                'type':'GET',
                'columns': [
                    {
                        'data': 'codigo',
                        'visible': false
                    },
                    { 'data': 'descripcion' }
                ],
                'columnDefs': [
                    {
                        'width': "130px",
                        'targets': [2],
                        'render': function (data, type, row) {
                            return '<a style="padding:0px;margin-left:10px;" class="btn btn-default" id="btnEditar" href="@Url.Action("Edit", "GrupoUsuario")/' + row.codigo + '"><div class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="Editar"></div></a>'
                                    +'<a style="padding:0px;margin-left:20px;" class="btn btn-default" id="btnDetalle" href="@Url.Action("Details", "GrupoUsuario")/' + row.codigo + '"><div class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Detalle"></div></a>'
                                    +'<a style="padding:0px;margin-left:20px;" class="btn btn-default" id="btnEliminar" href="@Url.Action("Delete", "GrupoUsuario")/' + row.codigo + '"><div class="fa fa-trash-alt" data-toggle="tooltip" data-placement="top" title="Eliminar"></div></a>';
                        }
                    }
                ]
            });

            $('[data-toggle="tooltip"]').tooltip();

        });

    </script>
}