CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Controllers/EntradaCompletaController.cs
using CL.Scotiabank.LegalPartner.CabeceraSglAPI.Transversal.DTO;
using CL.Scotiabank.LegalPartner.ConsultaAPI.Transversal.DTO;
using CL.Scotiabank.LegalPartner.PoderYRevocacionesAPI.Transversal.DTO;
using CL.Scotiabank.LegalPartner.SGL.APP;
using CL.Scotiabank.LegalPartner.SGL.Transversal.DTO;
using CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.DTO.EntradaCompleta;
using CL.Scotiabank.LegalPartner.SGL.Transversal.Utilities;
using Microsoft.AspNetCore.Mvc;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Resources = CL.Scotiabank.LegalPartner.SGL.Transversal.Utilities.Resources;

namespace CL.Scotiabank.LegalPartner.SGL.Web.Areas.EntradaCompleta.Controllers
{

    [ActionsFilter]
    public class EntradaCompletaController : Controller
    {
        #region Members

        private IEntradaCompletaAPP _entradaCompletaAPP;
        private dynamic logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
        private readonly string tituloMensajeError = Resources.TituloMensajeError;
        private readonly string cuerpoMensajeError = Resources.CuerpoMensajeError;
        #endregion

        #region Constructor

        public EntradaCompletaController(IEntradaCompletaAPP consultaPoderesAPP)
        {
            this._entradaCompletaAPP = consultaPoderesAPP;
        }

        #endregion

        /// <summary>
        /// Index de entrada completa
        /// </summary>
        /// <param name="paramCargaIndex"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Index(IngresarSGLDTO paramCargaIndex)
        {

            ConsultaPersonaDatosDTO paramPersonaRetorno = new ConsultaPersonaDatosDTO();

            try
            {
                int codEstadoLegal = 0;
                VerInformeCapitalDTO InformeDto = new VerInformeCapitalDTO();

                UsuarioConsultaDTORequest paramPersona = new UsuarioConsultaDTORequest
                {
                    Rut = int.Parse(paramCargaIndex.Rut.Replace(".", "").Split("-")[0]),//17310107,// 76005049, //76005049, //1, 
                    Nombre = string.Empty,
                    ApellidoPaterno = string.Empty,
                    ApellidoMaterno = string.Empty,
                    CantidadRegistros = 0
                };

                BasePropertiesDTO datosPersonaRetorno = this._entradaCompletaAPP.ObtenerDatosPersona(paramPersona);

                BasePropertiesDTO datosPersonaJuridicaRetorno = this._entradaCompletaAPP.ConsultaPersonaJuridicaDatos(datosPersonaRetorno.Resultado[0].CodigoPersona);
                ViewBag.NombreLegal = datosPersonaJuridicaRetorno.Resultado[0].NombreLegal;
                ViewBag.CodigoTipoPersona = datosPersonaJuridicaRetorno.Resultado[0].CodigoTipoPersona;
                codEstadoLegal = Convert.ToInt32(datosPersonaJuridicaRetorno.Resultado[0].CodigoEstadoLegal).Equals(0) ? 1 : Convert.ToInt32(datosPersonaJuridicaRetorno.Resultado[0].CodigoEstadoLegal);
                ViewBag.CodigoEstadoLegal = codEstadoLegal;

                BasePropertiesDTO datosComboRetorno = this._entradaCompletaAPP.GetListaEstadoLegal();
                ViewBag.DescEstadoLegal = ((IEnumerable<ConsultaListaEstadoLegalDTOResponse>)datosComboRetorno.Resultado).Where(x => x.Codigo == codEstadoLegal).FirstOrDefault().Descripcion;
                ViewBag.Sgl = paramCargaIndex.IdSGL;
                InformeDto.SGL = paramCargaIndex.IdSGL;
                if (paramCargaIndex.Entrada == "C")
                {
                    InformeDto.Entrada = "EC";
                }
                else
                {
                    InformeDto.Entrada = "N";
                }
                ViewBag.Entrada = InformeDto.Entrada;

                return View("Index", (ConsultaPersonaDatosDTO)datosPersonaRetorno.Resultado[0]);

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = tituloMensajeError;
                @TempData["CuerpoMensaje"] = cuerpoMensajeError;
                logger.Error(ex, "Stopped program because of exception");

                return RedirectToAction("Home", "Login", new { area = "Login" });
            }
           
        }
        
        /// <summary>
        /// Lista los documentos en el DataTable de legalizacion.
        /// </summary>
        /// <param name="codigoPersona"></param>
        /// <returns></returns>
        public JsonResult ListaDocumentos(int codigoPersona)
        {
            IList<ListaDocumentoDTO> lstDocumentos = new List<ListaDocumentoDTO>();
            BasePropertiesDTO datosPersonaRetorno = this._entradaCompletaAPP.ObtenerListadoDocumentos(codigoPersona);

            if (datosPersonaRetorno != null)
            {
                lstDocumentos = _entradaCompletaAPP.MapeaListaDocumentos((IEnumerable<DocumentoDTOResponse>)datosPersonaRetorno.Resultado);
            }

            return this.Json(new
            {
                data = lstDocumentos
            });
        }

        /// <summary>
        /// Json que recibe el objeto para luego enviarlo al modal Consulta Poder
        /// </summary>
        /// <param name="datosModal"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult EnviaDataVistaParcial([FromBody]EntradaCompletaDTO datosModal)
        {
            bool exitoso = false;
            if (ModelState.IsValid)
            {
                exitoso = true;
                return Json(new { Exitoso = exitoso, Data = datosModal });                
            }
            else
            {
                return Json(new { Exitoso = exitoso, Data = datosModal });
            }
        }

        [HttpPost]
        public JsonResult EnviaDataVistaParcialAgregar([FromBody]DatosModalAgregarDocumEscriDTO datosModal)
        {
            bool exitoso = false;
            if (ModelState.IsValid)
            {
                exitoso = true;
                return Json(new { Exitoso = exitoso, Data = datosModal });
            }
            else
            {
                return Json(new { Exitoso = exitoso, Data = datosModal });
            }
        }

        /// <summary>
        /// Carga inicial del Tab de Constitucion y legalizacion
        /// </summary>
        /// <param name="paramUsuario"></param>
        /// <returns></returns>
        public IActionResult ConstitucionYLegalizacion(EntradaCompletaDTO paramUsuario)
        {
            ConstitucionYLegalizacionDTO paramConsLEg = new ConstitucionYLegalizacionDTO();
            string codTipoPersonaFLEG = string.Empty;
            int codTipoPersona = 0;
            int codEPV = 0;
            //Cargar Documentos

            try
            {
                BasePropertiesDTO datosPersonaRetorno = this._entradaCompletaAPP.ObtenerListadoDocumentos(paramUsuario.CodigoPersona);

                if (datosPersonaRetorno.Resultado.Count == 0)
                {
                    //Insertar el registro
                    IngresarDatosDocumentosDTO paramDocumento = new IngresarDatosDocumentosDTO
                    {
                        CodigoPersona = paramUsuario.CodigoPersona,
                        IdSGL = paramUsuario.Sgl
                    };

                    paramDocumento = LlenaInsertarVacio(paramDocumento);

                    BasePropertiesDTO documentoRetorno = this._entradaCompletaAPP.IngresarDatosDocumento(paramDocumento);
                    datosPersonaRetorno = this._entradaCompletaAPP.ObtenerListadoDocumentos(paramUsuario.CodigoPersona);
                }

                BasePropertiesDTO datosPersonaJuridicaRetorno = this._entradaCompletaAPP.ConsultaPersonaJuridicaDatos(paramUsuario.CodigoPersona);
                codTipoPersona = Convert.ToInt32(datosPersonaJuridicaRetorno.Resultado[0].CodigoTipoPersona);
                paramConsLEg.CodTipoPersona = codTipoPersona;

                BasePropertiesDTO datosTipoPersonaRetorno = this._entradaCompletaAPP.GetListadoTipoPersonaDetalle();
                if (codTipoPersona != 0)
                {
                    codTipoPersonaFLEG = ((IEnumerable<TipoPersonaDetalleDTOResponse>)datosTipoPersonaRetorno.Resultado).Where(x => x.Codigo == codTipoPersona.ToString()).FirstOrDefault().CodigoLegal;
                }


                paramConsLEg.TipoPersonaFLEG = codTipoPersonaFLEG.Trim();
                paramConsLEg.Sgl = paramUsuario.Sgl;
                paramConsLEg.intTipoLeg = ((IEnumerable<DocumentoDTOResponse>)datosPersonaRetorno.Resultado).Where(x => x.CodigoTipoLegal.Equals(1)).Count() > 0 ? 1 : 0;
                paramConsLEg.CodEPV = codEPV;
                paramConsLEg.CodigoEstadoLegal = datosPersonaJuridicaRetorno.Resultado[0].CodigoEstadoLegal;
                paramConsLEg.Estado = datosPersonaJuridicaRetorno.Resultado[0].Estado;
                paramConsLEg.FechaConsulta = datosPersonaRetorno.Resultado[0].FechaDocumento.ToString("dd/MM/yyyy").Replace('-', '/');
                paramConsLEg.IdPersona = datosPersonaRetorno.Resultado[0].CodigoPersona;
                ViewBag.lstDocumentos = datosPersonaRetorno.Resultado;

                return PartialView(paramConsLEg);

            }
            catch (Exception ex)
            {
                @TempData["Error"] = true;
                @TempData["TituloMensaje"] = tituloMensajeError;
                @TempData["CuerpoMensaje"] = cuerpoMensajeError;
                logger.Error(ex, "Stopped program because of exception");

                return PartialView(paramConsLEg);
                //return RedirectToAction("Home", "Login", new { area = "Login" });
            }
           
        }

        /// <summary>
        /// Llena objeto para ingresar un registro cuanto la SGL no contiene documentos
        /// </summary>
        /// <param name="paramDocumento"></param>
        /// <returns></returns>

CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Views/EntradaCompleta/ModalCambiarEstadoSGL.cshtml
@model List<CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.EstadoSGLDTO>
<div>
    <form class="col-xl-12 col-md-12 col-sm-12" id="formulario" align="center">
            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    @foreach (var item in Model)
                    {
                        <div class="custom-control custom-radio pl-0">
                            <input type="radio" class="custom-control-input radioEstado" id="@item.CodigoEstadoSGL"  name="RadioEstados">
                            <label class="custom-control-label" for="@item.CodigoEstadoSGL">@item.DescripcionEstadoSGL</label>
                        </div>
                    }
                </div>
            </div>
    </form>
    @*<div class="mt-3">
        <button id="btnmodal-cambiarEstado" type="button" class="btn btn-primary" disabled>Aceptar</button>
    </div>*@
</div>

<script type="text/javascript">

    if (@Model.Count>2) {
        $('.modal-content').css("height", "80%");
    } else {
        console.log("2 estados");
        $('.modal-content').removeAttr("style");
    }

    var codEstado = 0;

    $(".radioEstado").click(function () {
        codEstado = this.id;
        $("#btnmodal-cambiarEstado").attr("disabled", false);;
    });

    $("#btnmodal-cambiarEstado").click(function () {
        if (codEstado > 0) {
            $("#modal-estadosSGL").modal('hide')
            $.ajax({
                method: "POST",
                url: '@Url.Action("ModificarEstadoSGL", "EntradaCompleta")',
                dataType: 'json',
                data: {
                        codigoSGL: @Model[0].CodigoSGL,
                        codigoEstado: codEstado
                    }
                })
                .done(function (data) {

                    if (data.exitoso) {
                        mensaje = data.mensaje;
                        titulo = "Mensaje: Cambio de Estado";
                        MuestraMensajes(titulo, mensaje);
                    } else {
                        mensaje = data.mensaje;
                        titulo = "Mensaje: Cambio de Estado";
                        MuestraMensajes(titulo, mensaje);
                    }
                })
                .fail(function () {
                    $("#modal-estadosSGL").modal('hide')
                    $('#titulo-modal-mensaje').html('Mensaje: Advertencia');
                    $('#cuerpo-modal-mensaje').html('La eliminación no se realizó correctamente.');

                    $('#modal-mensaje').modal('show');
                });
        } else {
            $("#modal-estadosSGL").modal('hide')
            $('#titulo-modal-mensaje').html('Mensaje: Advertencia');
            $('#cuerpo-modal-mensaje').html('No ha seleccionado un estado para modificar el registro.');

            $('#modal-mensaje').modal('show');
        }
    })

</script>

CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Views/EntradaCompleta/ModalEliminaDocumento.cshtml
@model CL.Scotiabank.LegalPartner.SGL.Transversal.DTO.EliminarDocumentoDTO
@{
    ViewData["Title"] = "EliminarDocumento";
}

<div class="row" style="text-align:center; position:center; ">
    <hr />
    <div class="input-group">
        <div class="col-md-12">
            <form asp-action="EliminaDocumento" class="col-xl-12" id="formularioEliminarDocumento">
                @Html.HiddenFor(model => model.CodigoDocumento)

                <label class="control-label col-md-12" style="font-size: 15px;"> ¿Esta seguro que desea eliminar el Documento?'</label>
            </form>
        </div>
    </div>
</div>

CL.Scotiabank.LegalPartner.SGL.Web/Areas/EntradaCompleta/Views/EntradaCompleta/PoderesYRevocaciones.cshtml
@{
    ViewData["Title"] = "PoderesYRevocaciones";
}

<h2>PoderesYRevocaciones</h2>